# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c1047665909d6a685eb91898c59c431faf57631e8de8dd2e3206fcbf1e35cd537c9f2740976fd7590214d3117c450178d4ddc45d85dae8b7382abb94e26ca7

test:
  secret_key_base: d07a4d2538e6b97701ecaff8a2d2dd4b3ad3af0c54ec05686c8f8fe60f33fbe9cb2fbb2c7ced9eb8df37d4b5f597f0bf8823161158184fb6d2e56a5428f6d432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
